namespace NoP77svk.TibcoDV.API
{
    public enum TdvResourceTypeEnumAgr
    {
        Unknown,
        UnknownContainer,
        DataSourceRelational,
        DataSourceCompositeWebService,
        DataSourceExcel,
        DataSourceFile,
        DataSourceWsWsdl,
        DataSourceXmlFile,
        UnknownDataSource,
        Catalog,
        Schema,
        Folder,
        Table,
        View,
        UnknownTable,
        StoredProcedureSQL,
        StoredProcedureOther,
        PublishedTableOrView,
        PublishedStoredProcedure,
        PublishedResource,
        DefinitionSet,
        Model,
        Trigger
    }
}
