on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Update private NuGet source
      run: |
        dotnet nuget add source --name NoP77svk --username anyone --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text "https://nuget.pkg.github.com/nop77svk/index.json" \
        || dotnet nuget update source NoP77svk --username anyone --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --source "https://nuget.pkg.github.com/nop77svk/index.json"
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: |
        dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NoP77svk.*.${VERSION}.nupkg --source https://nuget.pkg.github.com/nop77svk/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Windows x64 Build
      run: |
        dotnet publish tdvcli -c Release -o ./_publish.win-x64 -r win-x64 --self-contained
        cd ./_publish.win-x64
        tar cv . | gzip -9c > tdvcli.${VERSION}.win.x64.tgz
        cd ..
    - name: Linux x64 Build
      run: |
        dotnet publish tdvcli -c Release -o ./_publish.linux-x64 -r linux-x64 --self-contained
        cd ./_publish.linux-x64
        tar cv . | gzip -9c > tdvcli.${VERSION}.linux.x64.tgz
        cd ..
    - name: Portable Build
      run: |
        dotnet publish tdvcli -c Release -o ./_publish.portable -p:PublishTrimmed=false
        cd ./_publish.portable
        tar cv . | gzip -9c > tdvcli.${VERSION}.portable.tgz
        cd ..
